### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by diagonal404** [zerone-fg/fisheye_detection#1]
你好，请问你使用的是VOC360数据集吗，可以分享一下吗，现在下不到了

**Comment by zerone-fg** [comment]
链接：https://pan.baidu.com/s/19JfMutpwGc61x7xwsqbbxg 
提取码：s0ki

**Comment by GuanruTan** [comment]
> s0ki

Hi, can you provide the link again? The link failed. Thx.
